### ISSUE TITLE
Yolo version

### ISSUE THREAD

**Issue by pablodz** [marrabld/open_fish_classifier#2]
Hello there, I'm interested on your repo.
Which version of YOLO are the repo using?

**Comment by marrabld** [comment]
G'day @ZurMaD .  We have moved the development work on this project in house for the time being. Will likely put our latest developments here towards the end of the year.   We have been using YoloV3 for most of the work but recently tried YoloV4.  I don't think we saw any improvements in results.  I recommend starting with https://github.com/AlexeyAB  version of Yolo.  We have since implemented a purely Keras version of yolo.

**Comment by pablodz** [comment]
Excellent, thank you very much for the reply. Greetings from Peru...

**Comment by marrabld** [comment]
Hola desde Australia Occidental. Disfrute mi tiempo en Cusco y los Andes. Muy benito.
